### ISSUE TITLE
[0.4.10] Unknown key:"Error while running the on_init: __EvoGUI__/evoGUI.lua:182: Unkown style EvoGUI_expando_closed"

### ISSUE THREAD

**Issue by mdPlusPlus** [narc0tiq/evoGUI#46]
Hi,

I am getting this error when trying to load my save game.
The map I am trying to load is vanilla 0.12.22. I am running the 64-bit version under Windows 7.
![evogui](https://cloud.githubusercontent.com/assets/9272131/12542901/9006c7be-c329-11e5-8f8e-80e2799b825a.PNG)

**Comment by narc0tiq** [comment]
Strange, the style is [right there in prototypes/styles.lua](https://github.com/narc0tiq/evoGUI/blob/0de6ed4105ec79ab27f9606bf84a3cb1c6342706/prototypes/styles.lua#L45), and [referenced by data.lua](https://github.com/narc0tiq/evoGUI/blob/0de6ed4105ec79ab27f9606bf84a3cb1c6342706/data.lua) as it should be.

...on further thought, a similar issue has appeared before: <http://www.factorioforums.com/forum/viewtopic.php?f=53&t=15982> -- Peter34's solution was to extract the mod folder from the ZIP archive (he also re-downloaded, but it's not likely the file would've gotten that corrupted in transit).

I'm unclear on what's causing this, and if that fix works for you, it still will have only happened twice in almost 6,000 downloads, which is honestly rather unusual. Could be something strange with Factorio's ZIP handling on some platforms, maybe? Possibly even just one platform in particular. Whatever the cause, it's unfortunately not something I can control from within the mod.

But please do let me know whether running with a bare mod folder instead of from the zip (or vice-verse! Stranger things have happened!) fixes the issue for you.

**Comment by mdPlusPlus** [comment]
Well, actually after a restart of Factorio it works flawless.
It seems the error only appears when you activate the mod and try to start/load a game without restarting the game before. Maybe this helps with narrowing it down.

**Comment by narc0tiq** [comment]
Uh, yeah, that's not something Factorio supports at all. I'm surprised it let you try loading the game without restarting.

Either way, thanks for checking again.

**Comment by mdPlusPlus** [comment]
Well, it works with other mods. [Factorio Maps](http://www.factorioforums.com/forum/viewtopic.php?f=92&t=14582) for example.
