### ISSUE TITLE
Is this mod actively supported?

### ISSUE THREAD

**Issue by MisterFister2016** [narc0tiq/evoGUI#79]
Most recent activity seems dated.  Interest caused by recent release of basegame v0.17.

**Comment by narc0tiq** [comment]
Hi, and thanks for your interest! As it happens, support is currently greatly limited by my day job and other commitments, which also prevent me from maintaining any running games of Factorio. I hadn't even known 0.17 was out until narc0tiq/YARM#87.

As I expressed there, I'm happy to accept a pull request if anyone wants to do the port to 0.17 before I can. Otherwise, I'll get around to it as time allows; I can't offer any specific promises.
